(function () {
  const API = (location.hostname === "127.0.0.1" || location.hostname === "localhost")
    ? "/api"
    : "https://api.transitous.org/api";
  const UA_NOTE = "TbilisiTransitUI/1.4";

  /* Rough Tbilisi metro area */
  const TBILISI = {
    latMin: 41.60,
    latMax: 41.85,
    lonMin: 44.65,
    lonMax: 45.05,
    center: [41.7151, 44.8271],
    zoom: 12,
  };

  const PRESETS = {
    freedom: { name: "Freedom Square", nameKa: "თავისუფლების მოედანი", lat: 41.692738, lon: 44.802055, id: "ge-tbilisi-transport-company_1:3639", type: "STOP" },
    station: { name: "Station Square", nameKa: "სადგურის მოედანი", lat: 41.7221, lon: 44.797737, id: "ge-tbilisi-transport-company_1:metro_1_8", type: "STOP" },
  };

  /* Distinct colors for concurrent itineraries on the map + cards */
  const ITIN_COLORS = ["#3db8a0", "#5b8def", "#e07a3a", "#c45c9e"];

  const I18N = {
    en: {
      title: "Tbilisi Transit",
      from: "From",
      to: "To",
      go: "Plan trip",
      swap: "Swap",
      searching: "Searching…",
      planning: "Finding routes…",
      noResults: "No routes found. Try different places.",
      pickBoth: "Set From and To — search or tap the map.",
      error: "Something went wrong.",
      duration: "min",
      transfers0: "Direct",
      transfers1: "1 transfer",
      transfersN: (n) => n + " transfers",
      live: "Live",
      scheduled: "Scheduled",
      walk: "Walk",
      bus: "Bus",
      metro: "Metro",
      gondola: "Gondola",
      toStop: "to",
      for: "for",
      presetFS: "Freedom → Station",
      presetSF: "Station → Freedom",
      mapHintFrom: "Tap map to set From · drag pin to adjust",
      mapHintTo: "Tap map to set To · drag pin to adjust",
      more: "Paste a link · Examples",
      paste: "Paste a link",
      useAsFrom: "Use as start",
      useAsTo: "Use as destination",
      examples: "Examples",
      pasteEmpty: "Paste a Maps link or geo: first.",
      pasteBad: "Couldn’t read a Tbilisi location from that.",
      outsideCity: "That point is outside Tbilisi.",
      droppedFrom: "From updated",
      droppedTo: "To updated",
      sharedIn: "Opened shared location",
      edit: "Edit",
      expand: "Details",
      collapse: "Hide",
      routesFound: (n) => (n === 1 ? "1 route" : n + " routes"),
      droppedPin: "Dropped pin",
      sheetOpen: "Show planner",
      useMyLocation: "My location",
      locating: "Getting your location…",
      locatedFrom: "From set to your location",
      locatedTo: "To set to your location",
      geoDenied: "Location permission denied. Allow it in browser settings.",
      geoUnavailable: "Couldn’t get your location. Try again.",
      geoTimeout: "Location timed out. Try again.",
      geoUnsupported: "Location isn’t available in this browser.",
      geoOutside: "You’re outside Tbilisi — can’t plan from here.",
      geoNearOutside: "Near Tbilisi — pin set, but outside the usual area.",
      footer: '<a href="https://transitous.org/" target="_blank" rel="noopener">Transitous</a> · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OSM</a>',
    },
    ka: {
      title: "თბილისის ტრანსპორტი",
      from: "საიდან",
      to: "სადამდე",
      go: "მარშრუტის ძებნა",
      swap: "შეცვლა",
      searching: "ძებნა…",
      planning: "მარშრუტები…",
      noResults: "მარშრუტი ვერ მოიძებნა.",
      pickBoth: "აირჩიეთ საიდან და სადამდე — ძებნა ან რუკა.",
      error: "შეცდომა მოხდა.",
      duration: "წთ",
      transfers0: "პირდაპირი",
      transfers1: "1 გადასვლა",
      transfersN: (n) => n + " გადასვლა",
      live: "ცოცხალი",
      scheduled: "განრიგი",
      walk: "ფეხით",
      bus: "ავტობუსი",
      metro: "მეტრო",
      gondola: "გონდოლა",
      toStop: "მდე",
      for: "",
      presetFS: "თავისუფლება → სადგური",
      presetSF: "სადგური → თავისუფლება",
      mapHintFrom: "რუკაზე დააჭირეთ — საიდან",
      mapHintTo: "რუკაზე დააჭირეთ — სადამდე",
      more: "ბმულის ჩასმა · მაგალითები",
      paste: "ჩასვით ბმული",
      useAsFrom: "საწყისად",
      useAsTo: "დანიშნულებად",
      examples: "მაგალითები",
      pasteEmpty: "ჯერ ჩასვით Maps ბმული ან geo:.",
      pasteBad: "თბილისის ლოკაცია ვერ ამოვიკითხე.",
      outsideCity: "წერტილი თბილისის გარეთაა.",
      droppedFrom: "საწყისი განახლდა",
      droppedTo: "დანიშნულება განახლდა",
      sharedIn: "გაზიარებული ლოკაცია გაიხსნა",
      edit: "შეცვლა",
      expand: "დეტალები",
      collapse: "დამალვა",
      routesFound: (n) => n + " მარშრუტი",
      droppedPin: "პინი",
      sheetOpen: "გეგმარება",
      useMyLocation: "ჩემი ადგილმდებარეობა",
      locating: "ადგილმდებარეობის მიღება…",
      locatedFrom: "საწყისი — თქვენი ადგილი",
      locatedTo: "დანიშნულება — თქვენი ადგილი",
      geoDenied: "ადგილმდებარეობაზე უარი. ჩართეთ ბრაუზერის პარამეტრებში.",
      geoUnavailable: "ადგილმდებარეობა ვერ მივიღე. სცადეთ თავიდან.",
      geoTimeout: "ადგილმდებარეობის მოთხოვნა ამოიწურა.",
      geoUnsupported: "ბრაუზერი ადგილმდებარეობას არ უჭერს მხარს.",
      geoOutside: "თბილისის გარეთ ხართ — აქედან ვერ დავგეგმავ.",
      geoNearOutside: "თბილისთან ახლოს — პინი დასმულია, მაგრამ ჩვეულ ზონას გარეთ.",
      footer: '<a href="https://transitous.org/" target="_blank" rel="noopener">Transitous</a> · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OSM</a>',
    },
  };

  window.TT = { API, UA_NOTE, PRESETS, I18N, TBILISI, ITIN_COLORS };
})();
