(function () {
  const API = (location.hostname === "127.0.0.1" || location.hostname === "localhost")
    ? "/api"
    : "https://api.transitous.org/api";
  const UA_NOTE = "TbilisiTransitUI/1.7";

  /* Rough Tbilisi metro area */
  const TBILISI = {
    latMin: 41.60,
    latMax: 41.85,
    lonMin: 44.65,
    lonMax: 45.05,
    center: [41.7151, 44.8271],
    zoom: 12,
  };

  const PRESETS = {
    freedom: { name: "Freedom Square", nameKa: "თავისუფლების მოედანი", lat: 41.692738, lon: 44.802055, type: "STOP" },
    station: { name: "Station Square", nameKa: "სადგურის მოედანი", lat: 41.7221, lon: 44.797737, type: "STOP" },
  };

  /*
   * Route option palette: evenly bright, clearly distinct hues
   * (red, green, blue, amber, purple, cyan, pink). Lines get a theme-aware
   * casing so they read on both the light and the dimmed dark map.
   * Walk legs are always dashed neutral gray.
   */
  const ITIN_COLORS = ["#e5484d", "#2fa86b", "#3b82f6", "#f0a020", "#9b5de5", "#14b3c4", "#e5508f"];

  const I18N = {
    en: {
      title: "Tbilisi Transit",
      from: "From",
      to: "To",
      go: "Plan trip",
      swap: "Swap start and destination",
      searching: "Searching…",
      planning: "Finding routes…",
      noResults: "No routes found. Try different places.",
      pickBoth: "Set a start and a destination first.",
      error: "Something went wrong. Check your connection.",
      duration: "min",
      transfers0: "Direct",
      transfers1: "1 transfer",
      transfersN: (n) => n + " transfers",
      live: "Live",
      scheduled: "Scheduled",
      walk: "Walk",
      walkOnly: "Walking only — no transit needed",
      bus: "Bus",
      metro: "Metro",
      gondola: "Cable car",
      toStop: "to",
      presetFS: "Freedom Sq → Station Sq",
      presetSF: "Station Sq → Freedom Sq",
      chooseStart: "Where from?",
      chooseDestination: "Where to?",
      editStart: "Move start",
      editDest: "Move destination",
      fromHere: "From here",
      toHere: "To here",
      cancel: "Cancel",
      back: "Back",
      moveMap: "Move the map to place the pin",
      resolving: "Finding address…",
      searchAddr: "Search address or stop",
      searchFrom: "Start: address or stop",
      searchTo: "Destination: address or stop",
      myLocation: "My location",
      chooseOnMap: "Choose on map",
      recentPlaces: "Recent places",
      recentTrips: "Recent trips",
      stops: "Stops",
      places: "Places",
      stopKind: ["Bus stop", "Metro", "Cable car"],
      nothingFound: "Nothing found",
      offline: "Offline",
      offlineSearch: "Offline — showing stops only",
      offlineSaved: (t) => "Offline — saved results from " + t,
      savedResults: (t) => "Saved results from " + t,
      more: "More: paste a link · examples",
      paste: "Paste a link",
      useAsFrom: "Use as start",
      useAsTo: "Use as destination",
      examples: "Examples",
      pasteEmpty: "Paste a Maps link or geo: first.",
      pasteBad: "Couldn’t read a Tbilisi location from that.",
      outsideCity: "That point is outside Tbilisi.",
      sharedIn: "Opened shared location",
      expand: "Details",
      routesFound: (n) => (n === 1 ? "1 route" : n + " routes"),
      droppedPin: "Pinned place",
      nearStop: (s) => "Near " + s,
      peekSwipe: "Swipe up",
      locating: "Getting your location…",
      locateOn: "Show my location",
      locateFollow: "Following you — tap to stop",
      locateRecenter: "Tap to recenter",
      geoDenied: "Location permission denied. Allow it in browser settings.",
      geoUnavailable: "Couldn’t get your location. Try again.",
      geoTimeout: "Location timed out. Try again.",
      geoUnsupported: "Location isn’t available in this browser.",
      geoOutside: "You’re outside Tbilisi.",
      vehLive: (n) => n + " live " + (n === 1 ? "vehicle" : "vehicles"),
      vehSched: (n) => n + " by schedule",
      vehNone: "No vehicles on this route right now",
      vehNote: "Live = timing from TTC vehicle GPS (via Transitous); position estimated between stops.",
      yourBus: "your trip",
      language: "ქართული",
      langShort: "KA",
      attribution: '<a href="https://transitous.org/" target="_blank" rel="noopener">Transitous</a> · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · <a href="https://maplibre.org/" target="_blank" rel="noopener">MapLibre</a>',
    },
    ka: {
      title: "თბილისის ტრანსპორტი",
      from: "საიდან",
      to: "სადამდე",
      go: "მარშრუტის ძებნა",
      swap: "საწყისის და დანიშნულების შეცვლა",
      searching: "ძებნა…",
      planning: "მარშრუტების ძებნა…",
      noResults: "მარშრუტი ვერ მოიძებნა.",
      pickBoth: "ჯერ აირჩიეთ საწყისი და დანიშნულება.",
      error: "შეცდომა. შეამოწმეთ კავშირი.",
      duration: "წთ",
      transfers0: "პირდაპირი",
      transfers1: "1 გადაჯდომა",
      transfersN: (n) => n + " გადაჯდომა",
      live: "ცოცხალი",
      scheduled: "განრიგით",
      walk: "ფეხით",
      walkOnly: "მხოლოდ ფეხით — ტრანსპორტი არ არის საჭირო",
      bus: "ავტობუსი",
      metro: "მეტრო",
      gondola: "საბაგირო",
      toStop: "→",
      presetFS: "თავისუფლების მ. → სადგურის მ.",
      presetSF: "სადგურის მ. → თავისუფლების მ.",
      chooseStart: "საიდან?",
      chooseDestination: "სად მიდიხართ?",
      editStart: "საწყისის შეცვლა",
      editDest: "დანიშნულების შეცვლა",
      fromHere: "აქედან",
      toHere: "აქამდე",
      cancel: "გაუქმება",
      back: "უკან",
      moveMap: "გადაადგილეთ რუკა პინის დასასმელად",
      resolving: "მისამართის ძებნა…",
      searchAddr: "მისამართი ან გაჩერება",
      searchFrom: "საწყისი: მისამართი ან გაჩერება",
      searchTo: "დანიშნულება: მისამართი ან გაჩერება",
      myLocation: "ჩემი ადგილმდებარეობა",
      chooseOnMap: "რუკაზე არჩევა",
      recentPlaces: "ბოლო ადგილები",
      recentTrips: "ბოლო მარშრუტები",
      stops: "გაჩერებები",
      places: "ადგილები",
      stopKind: ["ავტობუსის გაჩერება", "მეტრო", "საბაგირო"],
      nothingFound: "ვერაფერი მოიძებნა",
      offline: "ოფლაინ",
      offlineSearch: "ოფლაინ — მხოლოდ გაჩერებები",
      offlineSaved: (t) => "ოფლაინ — შენახული შედეგები " + t,
      savedResults: (t) => "შენახული შედეგები " + t,
      more: "მეტი: ბმულის ჩასმა · მაგალითები",
      paste: "ჩასვით ბმული",
      useAsFrom: "საწყისად",
      useAsTo: "დანიშნულებად",
      examples: "მაგალითები",
      pasteEmpty: "ჯერ ჩასვით Maps ბმული ან geo:.",
      pasteBad: "თბილისის ლოკაცია ვერ ამოვიკითხე.",
      outsideCity: "წერტილი თბილისის გარეთაა.",
      sharedIn: "გაზიარებული ლოკაცია გაიხსნა",
      expand: "დეტალები",
      routesFound: (n) => n + " მარშრუტი",
      droppedPin: "მონიშნული ადგილი",
      nearStop: (s) => s + "-სთან",
      peekSwipe: "ზემოთ გასრიალება",
      locating: "ადგილმდებარეობის მიღება…",
      locateOn: "ჩემი ადგილმდებარეობის ჩვენება",
      locateFollow: "თქვენ მოგყვებით — შეეხეთ გასაჩერებლად",
      locateRecenter: "შეეხეთ ცენტრირებისთვის",
      geoDenied: "ადგილმდებარეობაზე წვდომა უარყოფილია. ჩართეთ ბრაუზერის პარამეტრებში.",
      geoUnavailable: "ადგილმდებარეობა ვერ მივიღე. სცადეთ თავიდან.",
      geoTimeout: "ადგილმდებარეობის მოთხოვნის დრო ამოიწურა.",
      geoUnsupported: "ბრაუზერი ადგილმდებარეობას არ უჭერს მხარს.",
      geoOutside: "თბილისის გარეთ ხართ.",
      vehLive: (n) => n + " ცოცხალი",
      vehSched: (n) => n + " განრიგით",
      vehNone: "ამ ხაზზე ახლა ტრანსპორტი არ ჩანს",
      vehNote: "ცოცხალი = დრო TTC-ის GPS-ით (Transitous); პოზიცია გაჩერებებს შორის შეფასებულია.",
      yourBus: "თქვენი რეისი",
      language: "English",
      langShort: "EN",
      attribution: '<a href="https://transitous.org/" target="_blank" rel="noopener">Transitous</a> · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · <a href="https://maplibre.org/" target="_blank" rel="noopener">MapLibre</a>',
    },
  };

  window.TT = { API, UA_NOTE, PRESETS, I18N, TBILISI, ITIN_COLORS };
})();
